# Generated by Django 3.2.8 on 2021-10-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-creating_date']},
        ),
    ]
